[tool.cibuildwheel]
# build="cp36-*64 cp37-*64 cp38-*64 cp39-*64 cp310-*64 cp311-*64"
build="cp38-*64"

[tool.cibuildwheel.linux]
archs = ["x86_64"]
before-build="bash scripts/install_manylinux_deps.sh"
skip="*-manylinux_i686 *musllinux*"

[tool.cibuildwheel.macos]
before-build="brew install boost cereal cmake fmt glog jpeg-turbo libpng lz4 xxhash zstd"
environment = "CMAKE_OSX_DEPLOYMENT_TARGET=11.0"
